#注册api
POST http://127.0.0.1:5000/auth/register HTTP/1.1
content-type: application/json

{
    "username": "root",
    "password": "rootroot1"
}

### 

#登录
POST http://127.0.0.1:5000/auth/login HTTP/1.1
content-type: application/json

{
    "username": "root",
    "password": "rootroot1"
}

### 登录出去

POST http://127.0.0.1:5000/auth/loginout HTTP/1.1
content-type: application/json

{
    
}

###

#测试个需要登录的界面
GET http://127.0.0.1:5000/test


###

#获取文件状态
POST http://127.0.0.1:5000/folder/files HTTP/1.1
Content-Type: application/json

{
    "year":2019
}

### 

#测试api连接
GET  http://192.168.56.101:5000/nav/classes
