#测试后端api,vscode 需要安装Rest Client插件

### 测试注册
POST http://127.0.0.1:5000/api/auth/register HTTP/1.1
content-type: application/json

{
    "username": "root",
    "password": "rootroot1"
}

### 

#登录
POST http://127.0.0.1:5000/api/auth/login HTTP/1.1
content-type: application/json

{
    "username": "formatfa",
    "password": "formatfa"
}

### 获取登录信息
GET http://127.0.0.1:5000/api/auth/session HTTP/1.1

### 登录出去

GET http://127.0.0.1:5000/api/auth/logout HTTP/1.1
content-type: application/json

{
    
}


### 测试获取班级数据

POST http://127.0.0.1:5000/api/nav/classes HTTP/1.1
content-type: application/json

{
    "college":"大数据与人工智能学院"
}