export const StudentData={
    //基本信息
    studentCard1:{
        "term1_avlscore":34,//第一学期综合素质平均分
        "term1_yranking":299,//第一学期综合素质在全院排名
        "term1_cranking":12,//第一学期综合素质在全班排名
    },
    studentCard2:{
      "term2_avlscore":33,//第一学期综合素质平均分
      "term2_yranking":333,//第二学期综合素质在全院排名
      "term2_cranking":11//第二学期综合素质在全班排名
  },//基本信息卡片
    suchindexscores:[
      {value:[1,3,3,1,2,1,0],name:'学院指标平均分'},
      {value:[4,3,1,1,2,1,0],name:'班级指标平均分'},
      {value:[1,4,3,2,1,1,0],name:'学生指标分数'}//各指标的分数
  ],//各指标雷达
    data1:{
    CollegeData:[
        {
        Collegindex:'身心健康',
        Collegscores:60,//指标的分数
        Collegranking:122//指标的排名
      },
      {
         Collegindex:'思想政治',
        Collegscores:60,
        Collegranking:122
      }]//各指标在全院排名
      
    },
    data2:{
        ClassData:[{
            Classindex:'身心健康',
            Classscores:60,////指标的分数
           Classranking:122////指标的分数
          },{
          Classindex:'思想政治',
            Classscores:60,
            Classranking:122
          }]//各指标在全班排名
    },
    scores:{
      score:40
    }
  }
